### ISSUE TITLE
Consider allowing callers of simpleion.dump to provide their own writer

### ISSUE THREAD

**Issue by zslayton** [amzn/ion-python#112]
`ion-hash-python` currently relies on the private-by-convention `_dump` method instead of the public `dump` method because the former [allows you to provide your own `writer`](https://github.com/amzn/ion-python/blob/9c6b74a3d561459c50150a2000b96587c83eddcb/amazon/ion/simpleion.py#L204).

We should investigate whether there are enough other use cases for providing a writer that we can add that to `dump`, allowing ion-hash-python to use the public version. (Alternatively, if there aren't other use cases, we could at least add a comment to `_dump` indicating that it is relied upon by a sibling project.)

**Comment by tgregg** [comment]
As discussed offline, we don't know of a use case for user-provided writer coroutines at this time, beyond ion-hash-python. We can reopen this if we learn of additional use cases.

In the meantime, we can address the root of the issue, which is that breaking changes to `_dump` cause ion-hash-python to break. See #113 .
