### ISSUE TITLE
IonPyOrderedDict to force sequence in ion serialization and deserialization for simpleion (Feature Request)

### ISSUE THREAD

**Issue by yosoufe** [amzn/ion-python#124]
Hello,

This is basically a feature request.

We are going to use ion in an application that on one side ion-c is used and the other side is ion-python. The message itself has a field called `type` and  the value is a SYMBOL.

The ion-c side is assuming specific order in receiving data for `STRUCT` messages. It assumes it receives the `type` field first and then based on the `type` it parses the rest of the message.

Now on the python side, I would like to create a message that follows the sequence that c-ion side expects. If I use normal `IonPyDict` I cannot specify the the order but If I change internal of `IonPyDict` to use `OrderedDict` instead of regular dictionary, I can force the order that I need in the message.

- What do you think about it? I believe `IonPyOrderedDict` could be useful in such a situation. 
- Is there something wrong with having `IonPyOrderedDict`? 
- Is there any better option that I am missing here?

Thanks
Yousof

**Comment by raganhan** [comment]
The whole team talked and we are OK with using `IonPyOrderedDict` as the default implementation for Ion structs

**Comment by yosoufe** [comment]
Thanks @raganhan 
I am thinking to open a PR. 

Which option do the team prefer to have:
Option 1:
Definition of a new class `IonPyOrderedDict` and a flag for `loads` to choose which one to create.

Option 2:
Just simply use `OrderedDict` instead of `dict` for the `MultiMap` class.

Thanks
Yousof

**Comment by tgregg** [comment]
@yosoufe 
Let's go with Option 2.

**Comment by yosoufe** [comment]
This is resolved by #125. Closing this. Thanks
