### ISSUE TITLE
Why `ion_type` needs to be specified separately?

### ISSUE THREAD

**Issue by yosoufe** [amzn/ion-python#137]
Hi,

I would like to know why in the following example the `ion_type` needs to be specified separately?

```py
from amazon.ion import simpleion as ion
from collections import OrderedDict
ion_sym = ion.IonPySymbol('SomeSymbol', None)
ion_sym.ion_type = ion.IonType.SYMBOL  # why this line cannot be inside the constructor of IonPy*?

ion_dict = ion.IonPyDict(OrderedDict([
    ("key1", 1),
    ("key2", 2),
    ("someSymbol", ion_sym),
]))
ion_dict.ion_type = ion.IonType.STRUCT # why this line cannot be inside the constructor of IonPy*?
ion_bytes = ion.dumps(ion_dict, binary=True)
```

Every time I create any `IonPy*` object I need to specify the `ion_type` as well. As far as I understand there is a 1 to 1 mapping between each `IonType` and `IonPy*` object. So that could be specified inside the constructor of `IonPy*` class. 

Currently if I do not specify `ion_type` I will get error messages during `ion.dumps`. And when my ion struct is large and nested, it is difficult to find were I missed specifying `ion_type` and also the error message does not give me any hint where I missed it. I have to manually check the complete code, to find where I missed it.

Thanks

**Comment by cheqianh** [comment]
Hi, different ion_types dump different ion-formatted stream.

For example, 
**IonPyNull** can be `null.bool`, `null.int`... by specifying the ion_type,  
**IonPyText('SomeSymbol')** can be either `SomeSymbol` if its ion_type is `IonType.SYMBOL` or `"SomeSymbol"` if its ion_type is `IonType.STRING`, etc.

Refer to [conversion table](https://github.com/amzn/ion-python/blob/a14882559e77dbac74ade54d4a5cf28a0cf01a1d/amazon/ion/simpleion.py#L54) for more details.

**Comment by yosoufe** [comment]
Ok. Thanks. So it is not 1:1 as I thought. Is it possible to generate a better error message to make it easier to find where I am missing the `ion_type`? for example now this code
```.py
from amazon.ion import simpleion as ion
from collections import OrderedDict
ion_sym = ion.IonPySymbol('SomeSymbol', None)

ion_dict = ion.IonPyDict(OrderedDict([
    ("key1", 1),
    ("key2", 2),
    ("someSymbol", ion_sym),
]))
ion_dict.ion_type = ion.IonType.STRUCT
ion_bytes = ion.dumps(ion_dict, binary=True)
```

is generating this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yousof/.local/lib/python3.6/site-packages/amazon/ion/simpleion.py", line 289, in dumps
    tuple_as_sexp=tuple_as_sexp, omit_version_marker=omit_version_marker, **kw)
  File "/home/yousof/.local/lib/python3.6/site-packages/amazon/ion/simpleion.py", line 158, in dump
    _dump(obj, writer, from_type)
  File "/home/yousof/.local/lib/python3.6/site-packages/amazon/ion/simpleion.py", line 220, in _dump
    _dump(val, writer, from_type, field, in_struct=True, depth=depth+1)
  File "/home/yousof/.local/lib/python3.6/site-packages/amazon/ion/simpleion.py", line 212, in _dump
    if not null and ion_type.is_container:
AttributeError: 'NoneType' object has no attribute 'is_container'
```
From this error it is not easy to find where the error is happening. 

Thanks

**Comment by cheqianh** [comment]
I merged a PR #138 that shows detail error message.

Also I opened an issue #139: For some simple_ion constructors (python types and ion types are 1:1 mapping), its ion_type should be set up automatically.

Let me know if you have any future question.

**Comment by cheqianh** [comment]
I merged a PR #138 that shows detail error message.

Also I opened an issue #139: For some simple_ion constructors (python types and ion types are 1:1 mapping), its ion_type should be set up automatically.

Let me know if you have any future question.

**Comment by yosoufe** [comment]
That is amazing. thank you.

**Comment by cheqianh** [comment]
Forgot to mentioned that the most common way to construct a simple ion type is using [`from_value`](https://github.com/amzn/ion-python/blob/master/amazon/ion/simple_types.py#L90) where its ion_type is required.
