### ISSUE TITLE
Binary-ion with Flask http end node

### ISSUE THREAD

**Issue by mrx23dot** [amzn/ion-python#150]
What's the proper way to send and receive binary-ion with HTTP end-node (with GET/POST)?
For instance with Flask.

This is what I found for sending binaries as attachment, not sure if this is the correct way, or what's the content type.

```
@app.route('/images/<int:pid>.jpg', methods=["GET"])
def get(pid):
    response = make_response(get_binary(pid))
    
    response.headers.set('Content-Type', 'image/jpeg')
    response.headers.set(
        'Content-Disposition', 
        'attachment', 
        filename='%s.jpg' % pid
    )
    return response
    
@app.route("/", methods=["POST"])
def post():
    raw_data = flask.request.get_data()

```

Amazon seems to only use it with mqtt or similar.

**Comment by zslayton** [comment]
`application/ion` is included in the [Provisional Standard Media Type Registry](https://www.iana.org/assignments/provisional-standard-media-types/provisional-standard-media-types.xhtml) for binary Ion, but it has not yet been formally registered. We're tracking that effort in [this issue](https://github.com/amzn/ion-java/issues/82).

In the meantime, it looks like [the AWS SDK uses a combination](https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/aws-ion-protocol/src/main/java/software/amazon/awssdk/protocols/ion/AwsIonProtocolFactory.java#L38) of `application/x-amz-ion-` for binary and `text/x-amz-ion-` for text.
