### ISSUE TITLE
IonPyDict constructor does not set ion_type

### ISSUE THREAD

**Issue by andreasfragner** [amzn/ion-python#178]
Python version: 3.8.9
amazon.ion: 0.7.0

The `IonPyDict` constructor does not set the `ion_type` field, leading to downstream failures e.g. when trying to pass `IonPyDict` objects to `execute_statement` calls in `pyqldb`. `simpleion.loads`  produces identical objects, except with the `ion_type` field set correctly:
```
import json
from amazon.ion.simpleion import IonPyDict, loads, dumps

data = {'foo': 1, 'bar': 2}

x1 = IonPyDict(data)
x2 = loads(json.dumps(data))

assert x1 == x2

print('x1: ', x1.ion_type)
print('x2: ', x2.ion_type)
```
Output
```
x1:  None
x2:  <IonType.STRUCT: 12>
```

**Comment by cheqianh** [comment]
Hi @andreasfragner, in the https://github.com/amzn/ion-python/pull/173 we solved this issue. Would you mind trying it again with the latest version?

A little more technical details here, I tried above sample code with the latest ion-python:
```.py
import json
from amazon.ion.simpleion import IonPyDict, loads, dumps

data = {'foo': 1, 'bar': 2}

x1 = IonPyDict(data)
x2 = loads(json.dumps(data))

assert x1 == x2

print('x1: ', x1.ion_type)
print('x2: ', x2.ion_type)
```
Output:
```
x1:  <IonType.STRUCT: 12>
x2:  <IonType.STRUCT: 12>
```

**Comment by andreasfragner** [comment]
Thanks - I am on the latest release (0.7.0). When is the next release slated for?

**Comment by cheqianh** [comment]
I'll release it sometime soon. I'm working on some other issues right now but will start the 0.8.0 release in 1-2 weeks.

If this is an urgent fix, feel free to provide a little more details about your use case to help me prioritize the release.

**Comment by cheqianh** [comment]
Yes, we will work on scheduling time to release 0.8.0 soon.

**Comment by cheqianh** [comment]
ion-python 0.8.0 is released, refer to https://github.com/amzn/ion-python/releases/tag/v0.8.0 for more details.

Please feel free to reopen the issue if you need anything else.
