### ISSUE TITLE
Support text timestamps with more than 6 digits of fractional precision

### ISSUE THREAD

**Issue by tgregg** [amzn/ion-python#35]
The text reader does not support timestamps with greater than 6 digits fractional precision because Python's datetime only supports microsecond precision. Current logic raises an error instead of silently rounding/truncating.

Consider adding an extension to ion-python's `Timestamp` type to allow roundtripping of arbitrary fractional precision with full fidelity.

Successful resolution of this issue will involve removal of the following file from the `test_vectors.py` skip list:
`good/equivs/timestampsLargeFractionalPrecision.ion`

**Comment by zslayton** [comment]
This appears to have been closed by #100, which [removed `good/equivs/timestampsLargeFractionalPrecision.ion` from the skip list](https://github.com/amzn/ion-python/pull/100/files#diff-60f006a04937736c49b7592e4a7388f2L99).
