### ISSUE TITLE
Behavior change in bit_length implementation for python 2.6

### ISSUE THREAD

**Issue by atn34** [amzn/ion-python#69]
https://github.com/amzn/ion-python/blob/26cc0023cb4bfd82c1f2aec6d0b82205ffe92d6f/amazon/ion/util.py#L288

Implementations differ for 0 and negative numbers.
```
>>> (0).bit_length()
0
>>> len(bin(0)) - 2
1
>>> (-1).bit_length()
1
>>> len(bin(-1)) - 2
2
```

Not sure if this is important or not for the usages of bit_length, just thought I'd point it out.

**Comment by dlurton** [comment]
@atn34 Thanks for the heads up!
