### ISSUE TITLE
Add license to sdist

### ISSUE THREAD

**Issue by jayvdb** [amzn/ion-python#72]
For packaging, would you mind including the license, tests, etc into the sdist uploaded to PyPI.

See .spec at https://build.opensuse.org/package/show/home:jayvdb:moban/python-amazon.ion

**Comment by jayvdb** [comment]
Typically this is done by creating a `MANIFEST.in`, with rules for which files to include and which to exclude.

However I believe in the next release it can also be done by configuring setuptools a little. See [pypa/setuptools#1636](https://github.com/pypa/setuptools/issues/1636)

**Comment by tgregg** [comment]
Hi @jayvdb, I will look into this.

**Comment by tgregg** [comment]
@jayvdb , can you take a look at #76 and see if that will work for you?

**Comment by jayvdb** [comment]
I'm not sure about the side effects of using `data_files` for this - I've only used it to ship man pages.

**Comment by tgregg** [comment]
I don't think there are any side-effects. `data_files` seems to be an alternative to using `MANIFEST.in`. The files are just copied to the sdist.

**Comment by jayvdb** [comment]
Fun and games https://github.com/amzn/ion-python/pull/76#issuecomment-471315694

**Comment by tgregg** [comment]
Closed #76 in favor of #80 .

**Comment by tgregg** [comment]
ion-python 0.4.0 has been released.
