### ISSUE TITLE
Tests fail on i586 for Python 3.7

### ISSUE THREAD

**Issue by jayvdb** [amzn/ion-python#74]
```console
[  254s] ==================================== ERRORS ====================================
[  254s] ____________________ ERROR collecting tests/test_vectors.py ____________________
[  254s] tests/test_vectors.py:72: in <module>
[  254s]     getcontext().Emax = 100000000000000000
[  254s] E   OverflowError: Python int too large to convert to C ssize_t
[  254s] !!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
[  254s] =========================== 1 error in 13.40 seconds ===========================
```

https://build.opensuse.org/package/live_build_log/home:jayvdb:moban/python-amazon.ion/openSUSE_Tumbleweed/i586

**Comment by tgregg** [comment]
#75 attempts to fix this particular issue. I don't have access to this platform, though, so I could not verify or check for additional platform-specific errors.

**Comment by tgregg** [comment]
@jayvdb please reopen this issue if you encounter more errors related to i586.

**Comment by jayvdb** [comment]
Now I get a slightly different error:

```console
[  244s] ____________________ ERROR collecting tests/test_vectors.py ____________________
[  244s] tests/test_vectors.py:73: in <module>
[  244s]     getcontext().Emax = 2147483647
[  244s] E   ValueError: valid range for Emax is [0, MAX_EMAX]
```

https://build.opensuse.org/package/show/home:jayvdb:moban/python-amazon.ion

I cant re-open; insufficient rights ;-)

**Comment by tgregg** [comment]
I didn't know about the MAX_EMAX and MAX_EMIN constants; looks like they were [introduced](https://python.readthedocs.io/en/stable/whatsnew/3.3.html#id2) in 3.3. The values for a 32-bit architecture are
MAX_EMAX 425000000
MIN_EMIN -425000000

I'm not sure why these limits are less than the max size of an `ssize_t`, which seems to be the type they're stored in in C. Unfortunately, a few of our tests require values outside this range, meaning we need an architecture-specific skip list.
