### ISSUE TITLE
Helper to maintain 'Noneness' for `None` values converted to `IonPyNull`

### ISSUE THREAD

**Issue by jamesdbowman** [amzn/ion-python#87]
### Issue

simpleion does not provide a way for `None` python values to be converted back into `None` from `IonPyNull`.

The following example code prints:

```python
import io
import amazon.ion.simpleion as ion

def print_is_none(obj):
    if obj['NoneKey'] is None:
        print("Value is None")
    else:
        print("Value is not None")

myobj = {'NoneKey': None}
print_is_none(myobj)

fp = io.BytesIO()
ion.dump(myobj, fp)
ion_dict = ion.load(io.BytesIO(fp.getvalue()))

print_is_none(ion_dict)
```

prints:

```
Value is None
Value is not None
```

because `ion_dict['NoneKey']` returns an instance of `IonPyNull`.

### Expected Behavior

simpleion provides some mechanism by which customers can return to the original Python domain types, e.g. `None`ness is maintained across conversions to / from Ion.

**Comment by tgregg** [comment]
Is it sufficient to use [simple_types.is_null](https://github.com/amzn/ion-python/blob/master/amazon/ion/simple_types.py#L209)?

```python
def print_is_none(obj):
    if is_null(obj['NoneKey']):
        print("Value is None")
    else:
        print("Value is not None")
```

would print

```
Value is None
Value is None
```

**Comment by jamesdbowman** [comment]
Ah, that would do it for now. Thanks! Closing this issue.
