### ISSUE TITLE
Publish Documentation to Read the Docs

### ISSUE THREAD

**Issue by almann** [amzn/ion-python#9]
Publish generated documentation to [Read the Docs](http://docs.readthedocs.io/en/latest/index.html).

**Comment by Antrikshy** [comment]
If someone were to start a documentation stub, I'd love to contribute. I use this library and love writing documentation. 😀

**Comment by tgregg** [comment]
Documentation is available here: https://ion-python.readthedocs.io/en/latest/

New releases will cause ReadTheDocs to be notified to rebuild the docs. Now we can start adding to and improving the docs as necessary.
